type FaceVerificationProvider = "FACEPP";

interface FacePlusPlusDetectResponse {
  error_message?: string;
  faces?: {
    face_token?: string;
  }[];
}

interface FacePlusPlusCompareResponse {
  confidence?: number;
  error_message?: string;
  thresholds?: {
    "1e-3"?: number;
  };
}

export interface FaceVerificationScan {
  capturedAt: string;
  deviceLabel?: string;
  frameSignature: string;
  imageBase64: string;
}

export interface FaceEnrollmentResult {
  confidence: number;
  provider: FaceVerificationProvider;
  templateRef: string;
}

export interface FaceMatchResult {
  confidence: number;
  matched: boolean;
  provider: FaceVerificationProvider;
  requiredConfidence: number;
}

const configuredProviderRaw =
  process.env.WORKFORCE_FACE_PROVIDER?.trim().toUpperCase();

const faceppApiBaseUrl =
  process.env.WORKFORCE_FACEPP_API_BASE_URL?.trim() ??
  "https://api-us.faceplusplus.com";
const configuredFaceppTimeoutMs = Number.parseInt(
  process.env.WORKFORCE_FACEPP_TIMEOUT_MS ?? "",
  10,
);
const faceppTimeoutMs = Number.isFinite(configuredFaceppTimeoutMs)
  ? Math.max(configuredFaceppTimeoutMs, 1_000)
  : 4_000;

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

function normalizeBase64(value: string) {
  return value.replace(/^data:image\/[a-zA-Z0-9.+-]+;base64,/, "").trim();
}

function hasFacePlusPlusCredentials() {
  return Boolean(
    process.env.WORKFORCE_FACEPP_API_KEY?.trim() &&
      process.env.WORKFORCE_FACEPP_API_SECRET?.trim(),
  );
}

function getFacePlusPlusCredentials() {
  const key = process.env.WORKFORCE_FACEPP_API_KEY?.trim();
  const secret = process.env.WORKFORCE_FACEPP_API_SECRET?.trim();

  if (!key || !secret) {
    throw new Error(
      "Real face verification is enabled but Face++ credentials are missing. Set WORKFORCE_FACEPP_API_KEY and WORKFORCE_FACEPP_API_SECRET.",
    );
  }

  return { key, secret };
}

async function postFacePlusPlus<T>(
  endpoint: string,
  payload: Record<string, string>,
) {
  const body = new URLSearchParams(payload);
  const abortController = new AbortController();
  const timeout = setTimeout(() => abortController.abort(), faceppTimeoutMs);
  let response: Response;

  try {
    response = await fetch(`${faceppApiBaseUrl}${endpoint}`, {
      body: body.toString(),
      headers: {
        "content-type": "application/x-www-form-urlencoded",
      },
      method: "POST",
      signal: abortController.signal,
    });
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") {
      throw new Error(
        `Face verification provider timed out after ${faceppTimeoutMs}ms.`,
      );
    }

    throw error;
  } finally {
    clearTimeout(timeout);
  }

  let data: unknown = null;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const errorMessage =
      typeof data === "object" &&
      data !== null &&
      "error_message" in data &&
      typeof (data as { error_message?: unknown }).error_message === "string"
        ? (data as { error_message: string }).error_message
        : `Face verification provider request failed with status ${response.status}.`;

    throw new Error(errorMessage);
  }

  return data as T;
}

async function detectFaceToken(imageBase64: string) {
  const { key, secret } = getFacePlusPlusCredentials();
  const data = await postFacePlusPlus<FacePlusPlusDetectResponse>(
    "/facepp/v3/detect",
    {
      api_key: key,
      api_secret: secret,
      image_base64: normalizeBase64(imageBase64),
      return_landmark: "0",
    },
  );

  if (data.error_message) {
    throw new Error(data.error_message);
  }

  const faces = data.faces ?? [];
  if (faces.length === 0) {
    throw new Error(
      "No face was detected. Capture a clearer front-facing photo.",
    );
  }

  if (faces.length > 1) {
    throw new Error(
      "Multiple faces were detected. Ensure only one person is in frame.",
    );
  }

  const faceToken = faces[0]?.face_token;
  if (!faceToken) {
    throw new Error(
      "Face token could not be generated by the verification provider.",
    );
  }

  return faceToken;
}

function getConfiguredProvider(): FaceVerificationProvider {
  if (configuredProviderRaw === "FACEPP") {
    return configuredProviderRaw;
  }

  if (!configuredProviderRaw) {
    if (hasFacePlusPlusCredentials()) {
      return "FACEPP";
    }

    throw new Error(
      "Face verification requires Face++ credentials. Set WORKFORCE_FACE_PROVIDER=FACEPP with WORKFORCE_FACEPP_API_KEY and WORKFORCE_FACEPP_API_SECRET.",
    );
  }

  throw new Error(
    `Unsupported WORKFORCE_FACE_PROVIDER value "${configuredProviderRaw}". Use FACEPP.`,
  );
}

export async function enrollFaceTemplate(scan: FaceVerificationScan) {
  const configuredProvider = getConfiguredProvider();
  const faceToken = await detectFaceToken(scan.imageBase64);

  return {
    confidence: 0.99,
    provider: configuredProvider,
    templateRef: `facepp:${faceToken}`,
  } satisfies FaceEnrollmentResult;
}

export async function verifyFaceTemplate(args: {
  scan: FaceVerificationScan;
  storedTemplateRef: string;
}) {
  const configuredProvider = getConfiguredProvider();

  if (!args.storedTemplateRef.startsWith("facepp:")) {
    throw new Error(
      "This account has no Face++ enrollment token. Re-enroll your face profile.",
    );
  }

  const { key, secret } = getFacePlusPlusCredentials();
  const scanFaceToken = await detectFaceToken(args.scan.imageBase64);
  const comparison = await postFacePlusPlus<FacePlusPlusCompareResponse>(
    "/facepp/v3/compare",
    {
      api_key: key,
      api_secret: secret,
      face_token1: args.storedTemplateRef.slice("facepp:".length),
      face_token2: scanFaceToken,
    },
  );

  if (comparison.error_message) {
    throw new Error(comparison.error_message);
  }

  const confidenceRaw = comparison.confidence ?? 0;
  const providerThreshold = comparison.thresholds?.["1e-3"] ?? 75;
  const configuredThresholdRaw = Number(
    process.env.WORKFORCE_FACE_MATCH_THRESHOLD ?? "",
  );
  const thresholdRaw =
    Number.isFinite(configuredThresholdRaw) && configuredThresholdRaw > 0
      ? configuredThresholdRaw
      : providerThreshold;

  return {
    confidence: clamp(confidenceRaw / 100, 0, 1),
    matched: confidenceRaw >= thresholdRaw,
    provider: configuredProvider,
    requiredConfidence: clamp(thresholdRaw / 100, 0, 1),
  } satisfies FaceMatchResult;
}
